<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.cdiamondgit</groupId>
    <artifactId>java-encryption-cli</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <finalName>securefile</finalName>
        
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.5.1</version>

                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>io.github.cdiamondgit.securefile.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>